# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: i200635

on:
  push:
    branches: [ "i200635","20i-0864" ]
  pull_request:
    branches: [ "i200635","20i-0864" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install 
      run: |
       
       pip install -r requirements.txt
    - name: Lint 
      run: |
         make lint
    - name: Test 
      run: |
         make test
